name: collective-gift
recipe: laravel
config:
  webroot: app/public
  php: "8.3"
  database: mariadb
  via: apache
proxy:
  appserver:
    - collective-gift.lndo.site:80
    - collective-gift.lndo.site:443
